# Generated by Django 6.0.3 on 2026-06-21 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_admin_profiles_for_existing_users(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    profiles = [
        UserProfile(user_id=user_id, role="admin")
        for user_id in User.objects.values_list("id", flat=True)
        if not UserProfile.objects.filter(user_id=user_id).exists()
    ]
    if profiles:
        UserProfile.objects.bulk_create(profiles)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('requester', 'Requester')], db_index=True, default='admin', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_admin_profiles_for_existing_users, migrations.RunPython.noop),
    ]
