# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def approve_existing_profiles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    now = timezone.now()
    for user in User.objects.all().iterator():
        profile, _ = UserProfile.objects.get_or_create(user_id=user.id)
        if user.is_superuser:
            profile.role = "superadmin"
        profile.approval_status = "approved"
        profile.approved_at = profile.approved_at or now
        profile.rejection_reason = ""
        profile.save(update_fields=[
            "role",
            "approval_status",
            "approved_at",
            "rejection_reason",
            "updated_at",
        ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin", "Admin"),
                    ("requester", "Requester"),
                ],
                db_index=True,
                default="admin",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(approve_existing_profiles, migrations.RunPython.noop),
    ]
