# Generated by Django 6.0.3 on 2026-04-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Delta', 'Delta'), ('Gamma', 'Gamma'), ('Beta', 'Beta')], max_length=10)),
                ('number', models.CharField(max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['prefix', 'number'], name='hostels_roo_prefix_7a9945_idx')],
                'constraints': [models.UniqueConstraint(fields=('prefix', 'number'), name='unique_room')],
            },
        ),
    ]
