# Generated by Django 6.0.3 on 2026-08-18 10:45

from django.db import migrations, models


DELTA_ACTIVE_ROOMS = [
    ("101A", True, 1),
    ("101B", True, 2),
    ("101C", False, 3),
    ("101D", False, 4),
    ("102A", True, 5),
    ("102B", True, 6),
    ("102C", False, 7),
    ("102D", False, 8),
]


def fix_delta_room_catalog(apps, schema_editor):
    Room = apps.get_model("hostels", "Room")

    active_numbers = [number for number, _, _ in DELTA_ACTIVE_ROOMS]

    for number, has_attached_bath, display_order in DELTA_ACTIVE_ROOMS:
        Room.objects.update_or_create(
            prefix="Delta",
            number=number,
            defaults={
                "hostel_name": "Gaurlata",
                "room_type": "room",
                "has_attached_bath": has_attached_bath,
                "display_order": display_order,
                "is_active": True,
            },
        )

    Room.objects.filter(prefix="Delta").exclude(number__in=active_numbers).update(
        is_active=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_room_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(fix_delta_room_catalog, migrations.RunPython.noop),
    ]
