# Generated by Django 6.0.3 on 2026-04-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_at', models.DateTimeField(db_index=True)),
                ('departure_at', models.DateTimeField(db_index=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_designation', models.CharField(max_length=100)),
                ('visitor_organisation', models.CharField(max_length=100)),
                ('visitor_gender', models.CharField(max_length=20)),
                ('visitor_address', models.TextField()),
                ('visitor_mobile', models.CharField(max_length=20)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('purpose_of_visit', models.TextField()),
                ('requestee_name', models.CharField(max_length=100)),
                ('requestee_designation', models.CharField(max_length=100)),
                ('requestee_department', models.CharField(max_length=100)),
                ('requestee_mobile', models.CharField(max_length=20)),
                ('logistics_name', models.CharField(max_length=100)),
                ('logistics_designation', models.CharField(max_length=100)),
                ('logistics_mobile', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hostels.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('room_name', models.CharField(max_length=100)),
                ('arrival_at', models.DateTimeField()),
                ('departure_at', models.DateTimeField()),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_designation', models.CharField(max_length=100)),
                ('visitor_organisation', models.CharField(max_length=100)),
                ('visitor_gender', models.CharField(max_length=20)),
                ('visitor_address', models.TextField()),
                ('visitor_mobile', models.CharField(max_length=20)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('purpose_of_visit', models.TextField()),
                ('requestee_name', models.CharField(max_length=100)),
                ('requestee_designation', models.CharField(max_length=100)),
                ('requestee_department', models.CharField(max_length=100)),
                ('requestee_mobile', models.CharField(max_length=20)),
                ('logistics_name', models.CharField(max_length=100)),
                ('logistics_designation', models.CharField(max_length=100)),
                ('logistics_mobile', models.CharField(max_length=20)),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_records', to='bookings.booking')),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'status', 'arrival_at', 'departure_at'], name='bookings_bo_room_id_773745_idx'),
        ),
    ]
