# Generated by Django 6.0.3 on 2026-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='logistics_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='logistics_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='logistics_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_of_visit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requestee_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requestee_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requestee_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='visitor_organisation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='logistics_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='logistics_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='logistics_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='purpose_of_visit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='requestee_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='requestee_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='requestee_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_organisation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
