# Generated by Django 6.0.3 on 2026-04-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='purpose_of_visit',
        ),
        migrations.RemoveField(
            model_name='cancelledbooking',
            name='purpose_of_visit',
        ),
    ]
