# Generated by Django 6.0.3 on 2026-05-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_logistics_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visitor_gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cancelledbooking',
            name='visitor_gender',
            field=models.CharField(max_length=20),
        ),
    ]
