# Generated by Django 6.0.3 on 2026-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
