# Generated by Django 6.0.3 on 2026-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_created_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attender_count_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='attender_day_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='attender_general_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='attender_morning_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='attender_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='attender_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='visitor_category',
            field=models.CharField(blank=True, choices=[('institute_guest', 'Institute Guest'), ('conference_workshop_guest', 'Conference/Workshop Guest'), ('other_guest', 'Other Guest')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_count_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_day_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_general_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_morning_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_night_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='attender_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='visitor_category',
            field=models.CharField(blank=True, choices=[('institute_guest', 'Institute Guest'), ('conference_workshop_guest', 'Conference/Workshop Guest'), ('other_guest', 'Other Guest')], default='', max_length=50),
        ),
    ]
