# Generated by Django 6.0.3 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_attender_count_per_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="requestee_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
