# Generated by Django 6.0.3 on 2026-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_charge_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visitor_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
