# Generated by Django 6.0.3 on 2026-06-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_visitor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledbooking',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
