# Generated by Django 6.0.3 on 2026-06-20 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_budget_head_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('edited_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=150)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='bookings.booking')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-id'],
                'indexes': [models.Index(fields=['booking', 'edited_at'], name='bookings_bo_booking_1ae35f_idx')],
            },
        ),
    ]
