# Generated by Django 6.0.3 on 2026-06-21 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_booking_created_by_bookingedithistory'),
        ('hostels', '0003_room_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('arrival_at', models.DateTimeField(db_index=True)),
                ('departure_at', models.DateTimeField(db_index=True)),
                ('preferred_prefix', models.CharField(blank=True, default='', max_length=50)),
                ('room_preference_note', models.TextField(blank=True, default='')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_category', models.CharField(blank=True, choices=[('institute_guest', 'Institute Guest'), ('conference_workshop_guest', 'Conference/Workshop Guest'), ('other_guest', 'Other Guest')], default='', max_length=50)),
                ('visitor_designation', models.CharField(blank=True, default='', max_length=100)),
                ('visitor_organisation', models.CharField(blank=True, default='', max_length=100)),
                ('visitor_gender', models.CharField(blank=True, default='', max_length=20)),
                ('visitor_address', models.TextField(blank=True, default='')),
                ('visitor_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('visitor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('purpose_of_visit', models.TextField(blank=True, default='')),
                ('attender_required', models.BooleanField(default=False)),
                ('attender_count_per_day', models.PositiveIntegerField(default=0)),
                ('attender_general_shift', models.BooleanField(default=False)),
                ('attender_morning_shift', models.BooleanField(default=False)),
                ('attender_day_shift', models.BooleanField(default=False)),
                ('requestor_name', models.CharField(blank=True, default='', max_length=100)),
                ('requestor_designation', models.CharField(blank=True, default='', max_length=100)),
                ('requestor_department', models.CharField(blank=True, default='', max_length=100)),
                ('requestor_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('requestor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('approved_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='bookings.booking')),
                ('preferred_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_booking_requests', to='hostels.room')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(max_length=80)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.bookingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['requester', 'status', 'requested_at'], name='bookings_bo_request_832a92_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'requested_at'], name='bookings_bo_status_4bc198_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='bookings_us_user_id_b5957b_idx'),
        ),
    ]
