# Generated by Codex on 2026-06-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0019_bookingrequest_usernotification_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNotification",
        ),
    ]
