# Generated by Django 6.0.3 on 2026-06-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_delete_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('correction_required', 'Correction Required')], db_index=True, default='pending', max_length=20),
        ),
    ]
