# Generated by Django 6.0.3 on 2026-06-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_bookingrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='delete_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_booking_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deleted_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='deleted_by_role',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
