# Generated by Django 6.0.3 on 2026-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_bookingrequest_delete_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='visitor_address',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='visitor_address',
        ),
    ]
