# Generated by Django 6.0.3 on 2026-08-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_remove_booking_visitor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChargeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('purpose_event', models.TextField(blank=True, default='')),
                ('room_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attender_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_received_date', models.DateField(blank=True, null=True)),
                ('budget_head_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_sheet', to='bookings.booking')),
            ],
            options={
                'ordering': ['booking__departure_at', 'id'],
                'indexes': [models.Index(fields=['payment_received_date'], name='bookings_bo_payment_209489_idx'), models.Index(fields=['updated_at'], name='bookings_bo_updated_607787_idx')],
            },
        ),
    ]
