# Generated by Django 6.0.3 on 2026-08-18 13:24

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_bookingchargesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=bookings.models.generate_booking_share_token, max_length=64, unique=True)),
                ('share_type', models.CharField(choices=[('booking_sheet', 'Booking Sheet')], default='booking_sheet', max_length=40)),
                ('title', models.CharField(blank=True, default='Booking Sheet', max_length=120)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_booking_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['share_type', 'is_active', 'created_at'], name='bookings_bo_share_t_b922ff_idx')],
            },
        ),
    ]
