# Generated by Django 6.0.3 on 2026-08-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_bookingshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingshare',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingshare',
            name='share_type',
            field=models.CharField(choices=[('booking_sheet', 'Booking Sheet'), ('charge_sheet', 'Charges Sheet')], default='booking_sheet', max_length=40),
        ),
    ]
