# Generated by Django 6.0.3 on 2026-08-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_bookingshare_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='budget_head_department_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='budget_head_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='budget_head_project_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='budget_head_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('institute_head', 'Institute Head'), ('project_head', 'Project Head')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='budget_head_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
